// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class ActivateCategoryResponse {
    protected java.lang.Boolean activateCategoryResult;
    
    public ActivateCategoryResponse() {
    }
    
    public ActivateCategoryResponse(java.lang.Boolean activateCategoryResult) {
        this.activateCategoryResult = activateCategoryResult;
    }
    
    public java.lang.Boolean getActivateCategoryResult() {
        return activateCategoryResult;
    }
    
    public void setActivateCategoryResult(java.lang.Boolean activateCategoryResult) {
        this.activateCategoryResult = activateCategoryResult;
    }
}
