// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class ActivateTagResponse {
    protected java.lang.Boolean activateTagResult;
    
    public ActivateTagResponse() {
    }
    
    public ActivateTagResponse(java.lang.Boolean activateTagResult) {
        this.activateTagResult = activateTagResult;
    }
    
    public java.lang.Boolean getActivateTagResult() {
        return activateTagResult;
    }
    
    public void setActivateTagResult(java.lang.Boolean activateTagResult) {
        this.activateTagResult = activateTagResult;
    }
}
