// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class AppDownloadTag extends mstag.services.Tag {
    protected java.lang.String defaultUrl;
    protected java.lang.String WP7Url;
    protected java.lang.String IPhoneUrl;
    protected java.lang.String androidUrl;
    protected java.lang.String blackberryUrl;
    protected java.lang.String symbianUrl;
    protected java.lang.String j2MEUrl;
    
    public AppDownloadTag() {
    }
    
    public AppDownloadTag(java.lang.String title, java.lang.String interactionNote, mstag.services.TagStatus status, java.lang.String[] types, java.util.Calendar UTCStartDate, java.util.Calendar UTCEndDate, java.lang.String associatedPayload, java.lang.String defaultUrl, java.lang.String WP7Url, java.lang.String IPhoneUrl, java.lang.String androidUrl, java.lang.String blackberryUrl, java.lang.String symbianUrl, java.lang.String j2MEUrl) {
        this.title = title;
        this.interactionNote = interactionNote;
        this.status = status;
        this.types = types;
        this.UTCStartDate = UTCStartDate;
        this.UTCEndDate = UTCEndDate;
        this.associatedPayload = associatedPayload;
        this.defaultUrl = defaultUrl;
        this.WP7Url = WP7Url;
        this.IPhoneUrl = IPhoneUrl;
        this.androidUrl = androidUrl;
        this.blackberryUrl = blackberryUrl;
        this.symbianUrl = symbianUrl;
        this.j2MEUrl = j2MEUrl;
    }
    
    public java.lang.String getDefaultUrl() {
        return defaultUrl;
    }
    
    public void setDefaultUrl(java.lang.String defaultUrl) {
        this.defaultUrl = defaultUrl;
    }
    
    public java.lang.String getWP7Url() {
        return WP7Url;
    }
    
    public void setWP7Url(java.lang.String WP7Url) {
        this.WP7Url = WP7Url;
    }
    
    public java.lang.String getIPhoneUrl() {
        return IPhoneUrl;
    }
    
    public void setIPhoneUrl(java.lang.String IPhoneUrl) {
        this.IPhoneUrl = IPhoneUrl;
    }
    
    public java.lang.String getAndroidUrl() {
        return androidUrl;
    }
    
    public void setAndroidUrl(java.lang.String androidUrl) {
        this.androidUrl = androidUrl;
    }
    
    public java.lang.String getBlackberryUrl() {
        return blackberryUrl;
    }
    
    public void setBlackberryUrl(java.lang.String blackberryUrl) {
        this.blackberryUrl = blackberryUrl;
    }
    
    public java.lang.String getSymbianUrl() {
        return symbianUrl;
    }
    
    public void setSymbianUrl(java.lang.String symbianUrl) {
        this.symbianUrl = symbianUrl;
    }
    
    public java.lang.String getJ2MEUrl() {
        return j2MEUrl;
    }
    
    public void setJ2MEUrl(java.lang.String j2MEUrl) {
        this.j2MEUrl = j2MEUrl;
    }
}
