// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class Category {
    protected java.lang.String name;
    protected java.util.Calendar UTCStartDate;
    protected java.util.Calendar UTCEndDate;
    protected mstag.services.CategoryStatus categoryStatus;
    
    public Category() {
    }
    
    public Category(java.lang.String name, java.util.Calendar UTCStartDate, java.util.Calendar UTCEndDate, mstag.services.CategoryStatus categoryStatus) {
        this.name = name;
        this.UTCStartDate = UTCStartDate;
        this.UTCEndDate = UTCEndDate;
        this.categoryStatus = categoryStatus;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.util.Calendar getUTCStartDate() {
        return UTCStartDate;
    }
    
    public void setUTCStartDate(java.util.Calendar UTCStartDate) {
        this.UTCStartDate = UTCStartDate;
    }
    
    public java.util.Calendar getUTCEndDate() {
        return UTCEndDate;
    }
    
    public void setUTCEndDate(java.util.Calendar UTCEndDate) {
        this.UTCEndDate = UTCEndDate;
    }
    
    public mstag.services.CategoryStatus getCategoryStatus() {
        return categoryStatus;
    }
    
    public void setCategoryStatus(mstag.services.CategoryStatus categoryStatus) {
        this.categoryStatus = categoryStatus;
    }
}
