// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class CreateTag {
    protected mstag.services.UserCredential userCredential;
    protected java.lang.String categoryName;
    protected mstag.services.Tag tag;
    
    public CreateTag() {
    }
    
    public CreateTag(mstag.services.UserCredential userCredential, java.lang.String categoryName, mstag.services.Tag tag) {
        this.userCredential = userCredential;
        this.categoryName = categoryName;
        this.tag = tag;
    }
    
    public mstag.services.UserCredential getUserCredential() {
        return userCredential;
    }
    
    public void setUserCredential(mstag.services.UserCredential userCredential) {
        this.userCredential = userCredential;
    }
    
    public java.lang.String getCategoryName() {
        return categoryName;
    }
    
    public void setCategoryName(java.lang.String categoryName) {
        this.categoryName = categoryName;
    }
    
    public mstag.services.Tag getTag() {
        return tag;
    }
    
    public void setTag(mstag.services.Tag tag) {
        this.tag = tag;
    }
}
