// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class CreateTagResponse {
    protected java.lang.Boolean createTagResult;
    
    public CreateTagResponse() {
    }
    
    public CreateTagResponse(java.lang.Boolean createTagResult) {
        this.createTagResult = createTagResult;
    }
    
    public java.lang.Boolean getCreateTagResult() {
        return createTagResult;
    }
    
    public void setCreateTagResult(java.lang.Boolean createTagResult) {
        this.createTagResult = createTagResult;
    }
}
