// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class CreateCategoryResponse {
    protected java.lang.Boolean createCategoryResult;
    
    public CreateCategoryResponse() {
    }
    
    public CreateCategoryResponse(java.lang.Boolean createCategoryResult) {
        this.createCategoryResult = createCategoryResult;
    }
    
    public java.lang.Boolean getCreateCategoryResult() {
        return createCategoryResult;
    }
    
    public void setCreateCategoryResult(java.lang.Boolean createCategoryResult) {
        this.createCategoryResult = createCategoryResult;
    }
}
