// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class DeleteTagResponse {
    protected java.lang.Boolean deleteTagResult;
    
    public DeleteTagResponse() {
    }
    
    public DeleteTagResponse(java.lang.Boolean deleteTagResult) {
        this.deleteTagResult = deleteTagResult;
    }
    
    public java.lang.Boolean getDeleteTagResult() {
        return deleteTagResult;
    }
    
    public void setDeleteTagResult(java.lang.Boolean deleteTagResult) {
        this.deleteTagResult = deleteTagResult;
    }
}
