// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class FreeTextTag extends mstag.services.Tag {
    protected java.lang.String freeText;
    protected java.lang.String password;
    
    public FreeTextTag() {
    }
    
    public FreeTextTag(java.lang.String title, java.lang.String interactionNote, mstag.services.TagStatus status, java.lang.String[] types, java.util.Calendar UTCStartDate, java.util.Calendar UTCEndDate, java.lang.String associatedPayload, java.lang.String freeText, java.lang.String password) {
        this.title = title;
        this.interactionNote = interactionNote;
        this.status = status;
        this.types = types;
        this.UTCStartDate = UTCStartDate;
        this.UTCEndDate = UTCEndDate;
        this.associatedPayload = associatedPayload;
        this.freeText = freeText;
        this.password = password;
    }
    
    public java.lang.String getFreeText() {
        return freeText;
    }
    
    public void setFreeText(java.lang.String freeText) {
        this.freeText = freeText;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
}
