// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class GetBarcodeResponse {
    protected byte[] getBarcodeResult;
    
    public GetBarcodeResponse() {
    }
    
    public GetBarcodeResponse(byte[] getBarcodeResult) {
        this.getBarcodeResult = getBarcodeResult;
    }
    
    public byte[] getGetBarcodeResult() {
        return getBarcodeResult;
    }
    
    public void setGetBarcodeResult(byte[] getBarcodeResult) {
        this.getBarcodeResult = getBarcodeResult;
    }
}
