// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class GetBarcode {
    protected mstag.services.UserCredential userCredential;
    protected java.lang.String categoryName;
    protected java.lang.String tagName;
    protected java.lang.String[] imageType;
    protected java.lang.Float sizeInInches;
    protected mstag.services.DecorationType decorationsType;
    protected java.lang.Boolean isBlackWhite;
    
    public GetBarcode() {
    }
    
    public GetBarcode(mstag.services.UserCredential userCredential, java.lang.String categoryName, java.lang.String tagName, java.lang.String[] imageType, java.lang.Float sizeInInches, mstag.services.DecorationType decorationsType, java.lang.Boolean isBlackWhite) {
        this.userCredential = userCredential;
        this.categoryName = categoryName;
        this.tagName = tagName;
        this.imageType = imageType;
        this.sizeInInches = sizeInInches;
        this.decorationsType = decorationsType;
        this.isBlackWhite = isBlackWhite;
    }
    
    public mstag.services.UserCredential getUserCredential() {
        return userCredential;
    }
    
    public void setUserCredential(mstag.services.UserCredential userCredential) {
        this.userCredential = userCredential;
    }
    
    public java.lang.String getCategoryName() {
        return categoryName;
    }
    
    public void setCategoryName(java.lang.String categoryName) {
        this.categoryName = categoryName;
    }
    
    public java.lang.String getTagName() {
        return tagName;
    }
    
    public void setTagName(java.lang.String tagName) {
        this.tagName = tagName;
    }
    
    public java.lang.String[] getImageType() {
        return imageType;
    }
    
    public void setImageType(java.lang.String[] imageType) {
        this.imageType = imageType;
    }
    
    public java.lang.Float getSizeInInches() {
        return sizeInInches;
    }
    
    public void setSizeInInches(java.lang.Float sizeInInches) {
        this.sizeInInches = sizeInInches;
    }
    
    public mstag.services.DecorationType getDecorationsType() {
        return decorationsType;
    }
    
    public void setDecorationsType(mstag.services.DecorationType decorationsType) {
        this.decorationsType = decorationsType;
    }
    
    public java.lang.Boolean getIsBlackWhite() {
        return isBlackWhite;
    }
    
    public void setIsBlackWhite(java.lang.Boolean isBlackWhite) {
        this.isBlackWhite = isBlackWhite;
    }
}
