// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class GetTagIdResponse {
    protected java.lang.String getTagIdResult;
    
    public GetTagIdResponse() {
    }
    
    public GetTagIdResponse(java.lang.String getTagIdResult) {
        this.getTagIdResult = getTagIdResult;
    }
    
    public java.lang.String getGetTagIdResult() {
        return getTagIdResult;
    }
    
    public void setGetTagIdResult(java.lang.String getTagIdResult) {
        this.getTagIdResult = getTagIdResult;
    }
}
