// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class PauseTagResponse {
    protected java.lang.Boolean pauseTagResult;
    
    public PauseTagResponse() {
    }
    
    public PauseTagResponse(java.lang.Boolean pauseTagResult) {
        this.pauseTagResult = pauseTagResult;
    }
    
    public java.lang.Boolean getPauseTagResult() {
        return pauseTagResult;
    }
    
    public void setPauseTagResult(java.lang.Boolean pauseTagResult) {
        this.pauseTagResult = pauseTagResult;
    }
}
