// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class PauseCategoryResponse {
    protected java.lang.Boolean pauseCategoryResult;
    
    public PauseCategoryResponse() {
    }
    
    public PauseCategoryResponse(java.lang.Boolean pauseCategoryResult) {
        this.pauseCategoryResult = pauseCategoryResult;
    }
    
    public java.lang.Boolean getPauseCategoryResult() {
        return pauseCategoryResult;
    }
    
    public void setPauseCategoryResult(java.lang.Boolean pauseCategoryResult) {
        this.pauseCategoryResult = pauseCategoryResult;
    }
}
