// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class ReceiverFault_Exception extends Exception {
    private java.lang.String errorMessage;
    private mstag.services.ReceiverFaultReason reason;
    
    
    public ReceiverFault_Exception(java.lang.String errorMessage, mstag.services.ReceiverFaultReason reason) {
        super(errorMessage);
        this.errorMessage = errorMessage;
        this.reason = reason;
    }
    
    public java.lang.String getErrorMessage() {
        return errorMessage;
    }
    
    public mstag.services.ReceiverFaultReason getReason() {
        return reason;
    }
}
