// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class SenderFault_Exception extends Exception {
    private java.lang.String errorMessage;
    private mstag.services.SenderFaultReason reason;
    
    
    public SenderFault_Exception(java.lang.String errorMessage, mstag.services.SenderFaultReason reason) {
        super(errorMessage);
        this.errorMessage = errorMessage;
        this.reason = reason;
    }
    
    public java.lang.String getErrorMessage() {
        return errorMessage;
    }
    
    public mstag.services.SenderFaultReason getReason() {
        return reason;
    }
}
