// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class Tag {
    protected java.lang.String title;
    protected java.lang.String interactionNote;
    protected mstag.services.TagStatus status;
    protected java.lang.String[] types;
    protected java.util.Calendar UTCStartDate;
    protected java.util.Calendar UTCEndDate;
    protected java.lang.String associatedPayload;
    
    public Tag() {
    }
    
    public Tag(java.lang.String title, java.lang.String interactionNote, mstag.services.TagStatus status, java.lang.String[] types, java.util.Calendar UTCStartDate, java.util.Calendar UTCEndDate, java.lang.String associatedPayload) {
        this.title = title;
        this.interactionNote = interactionNote;
        this.status = status;
        this.types = types;
        this.UTCStartDate = UTCStartDate;
        this.UTCEndDate = UTCEndDate;
        this.associatedPayload = associatedPayload;
    }
    
    public java.lang.String getTitle() {
        return title;
    }
    
    public void setTitle(java.lang.String title) {
        this.title = title;
    }
    
    public java.lang.String getInteractionNote() {
        return interactionNote;
    }
    
    public void setInteractionNote(java.lang.String interactionNote) {
        this.interactionNote = interactionNote;
    }
    
    public mstag.services.TagStatus getStatus() {
        return status;
    }
    
    public void setStatus(mstag.services.TagStatus status) {
        this.status = status;
    }
    
    public java.lang.String[] getTypes() {
        return types;
    }
    
    public void setTypes(java.lang.String[] types) {
        this.types = types;
    }
    
    public java.util.Calendar getUTCStartDate() {
        return UTCStartDate;
    }
    
    public void setUTCStartDate(java.util.Calendar UTCStartDate) {
        this.UTCStartDate = UTCStartDate;
    }
    
    public java.util.Calendar getUTCEndDate() {
        return UTCEndDate;
    }
    
    public void setUTCEndDate(java.util.Calendar UTCEndDate) {
        this.UTCEndDate = UTCEndDate;
    }
    
    public java.lang.String getAssociatedPayload() {
        return associatedPayload;
    }
    
    public void setAssociatedPayload(java.lang.String associatedPayload) {
        this.associatedPayload = associatedPayload;
    }
}
