// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class UpdateCategoryResponse {
    protected java.lang.Boolean updateCategoryResult;
    
    public UpdateCategoryResponse() {
    }
    
    public UpdateCategoryResponse(java.lang.Boolean updateCategoryResult) {
        this.updateCategoryResult = updateCategoryResult;
    }
    
    public java.lang.Boolean getUpdateCategoryResult() {
        return updateCategoryResult;
    }
    
    public void setUpdateCategoryResult(java.lang.Boolean updateCategoryResult) {
        this.updateCategoryResult = updateCategoryResult;
    }
}
