// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class UpdateTagResponse {
    protected java.lang.Boolean updateTagResult;
    
    public UpdateTagResponse() {
    }
    
    public UpdateTagResponse(java.lang.Boolean updateTagResult) {
        this.updateTagResult = updateTagResult;
    }
    
    public java.lang.Boolean getUpdateTagResult() {
        return updateTagResult;
    }
    
    public void setUpdateTagResult(java.lang.Boolean updateTagResult) {
        this.updateTagResult = updateTagResult;
    }
}
