// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class UpdateCategory {
    protected mstag.services.UserCredential userCredential;
    protected java.lang.String existingCategoryName;
    protected mstag.services.Category category;
    
    public UpdateCategory() {
    }
    
    public UpdateCategory(mstag.services.UserCredential userCredential, java.lang.String existingCategoryName, mstag.services.Category category) {
        this.userCredential = userCredential;
        this.existingCategoryName = existingCategoryName;
        this.category = category;
    }
    
    public mstag.services.UserCredential getUserCredential() {
        return userCredential;
    }
    
    public void setUserCredential(mstag.services.UserCredential userCredential) {
        this.userCredential = userCredential;
    }
    
    public java.lang.String getExistingCategoryName() {
        return existingCategoryName;
    }
    
    public void setExistingCategoryName(java.lang.String existingCategoryName) {
        this.existingCategoryName = existingCategoryName;
    }
    
    public mstag.services.Category getCategory() {
        return category;
    }
    
    public void setCategory(mstag.services.Category category) {
        this.category = category;
    }
}
