// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class URITag extends mstag.services.Tag {
    protected java.lang.String medFiUrl;
    
    public URITag() {
    }
    
    public URITag(java.lang.String title, java.lang.String interactionNote, mstag.services.TagStatus status, java.lang.String[] types, java.util.Calendar UTCStartDate, java.util.Calendar UTCEndDate, java.lang.String associatedPayload, java.lang.String medFiUrl) {
        this.title = title;
        this.interactionNote = interactionNote;
        this.status = status;
        this.types = types;
        this.UTCStartDate = UTCStartDate;
        this.UTCEndDate = UTCEndDate;
        this.associatedPayload = associatedPayload;
        this.medFiUrl = medFiUrl;
    }
    
    public java.lang.String getMedFiUrl() {
        return medFiUrl;
    }
    
    public void setMedFiUrl(java.lang.String medFiUrl) {
        this.medFiUrl = medFiUrl;
    }
}
