// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class UserCredential {
    protected java.lang.String accessToken;
    
    public UserCredential() {
    }
    
    public UserCredential(java.lang.String accessToken) {
        this.accessToken = accessToken;
    }
    
    public java.lang.String getAccessToken() {
        return accessToken;
    }
    
    public void setAccessToken(java.lang.String accessToken) {
        this.accessToken = accessToken;
    }
}
