// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package mstag.services;


public class VCardTag extends mstag.services.Tag {
    protected boolean hasFile;
    protected byte[] vcfData;
    protected java.lang.String firstName;
    protected java.lang.String lastName;
    protected java.lang.String email;
    protected java.lang.String company;
    protected java.lang.String workPhone;
    protected java.lang.String mobilePhone;
    protected java.lang.String fax;
    protected java.lang.String street;
    protected java.lang.String city;
    protected java.lang.String state;
    protected java.lang.String zip;
    protected java.lang.String country;
    protected java.lang.String webPage;
    protected java.lang.String password;
    protected java.lang.String homePhone;
    protected java.lang.String department;
    protected java.lang.String jobTitle;
    protected java.lang.String IMAddress;
    
    public VCardTag() {
    }
    
    public VCardTag(java.lang.String title, java.lang.String interactionNote, mstag.services.TagStatus status, java.lang.String[] types, java.util.Calendar UTCStartDate, java.util.Calendar UTCEndDate, java.lang.String associatedPayload, boolean hasFile, byte[] vcfData, java.lang.String firstName, java.lang.String lastName, java.lang.String email, java.lang.String company, java.lang.String workPhone, java.lang.String mobilePhone, java.lang.String fax, java.lang.String street, java.lang.String city, java.lang.String state, java.lang.String zip, java.lang.String country, java.lang.String webPage, java.lang.String password, java.lang.String homePhone, java.lang.String department, java.lang.String jobTitle, java.lang.String IMAddress) {
        this.title = title;
        this.interactionNote = interactionNote;
        this.status = status;
        this.types = types;
        this.UTCStartDate = UTCStartDate;
        this.UTCEndDate = UTCEndDate;
        this.associatedPayload = associatedPayload;
        this.hasFile = hasFile;
        this.vcfData = vcfData;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.company = company;
        this.workPhone = workPhone;
        this.mobilePhone = mobilePhone;
        this.fax = fax;
        this.street = street;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.country = country;
        this.webPage = webPage;
        this.password = password;
        this.homePhone = homePhone;
        this.department = department;
        this.jobTitle = jobTitle;
        this.IMAddress = IMAddress;
    }
    
    public boolean isHasFile() {
        return hasFile;
    }
    
    public void setHasFile(boolean hasFile) {
        this.hasFile = hasFile;
    }
    
    public byte[] getVcfData() {
        return vcfData;
    }
    
    public void setVcfData(byte[] vcfData) {
        this.vcfData = vcfData;
    }
    
    public java.lang.String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public java.lang.String getLastName() {
        return lastName;
    }
    
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public java.lang.String getEmail() {
        return email;
    }
    
    public void setEmail(java.lang.String email) {
        this.email = email;
    }
    
    public java.lang.String getCompany() {
        return company;
    }
    
    public void setCompany(java.lang.String company) {
        this.company = company;
    }
    
    public java.lang.String getWorkPhone() {
        return workPhone;
    }
    
    public void setWorkPhone(java.lang.String workPhone) {
        this.workPhone = workPhone;
    }
    
    public java.lang.String getMobilePhone() {
        return mobilePhone;
    }
    
    public void setMobilePhone(java.lang.String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    
    public java.lang.String getFax() {
        return fax;
    }
    
    public void setFax(java.lang.String fax) {
        this.fax = fax;
    }
    
    public java.lang.String getStreet() {
        return street;
    }
    
    public void setStreet(java.lang.String street) {
        this.street = street;
    }
    
    public java.lang.String getCity() {
        return city;
    }
    
    public void setCity(java.lang.String city) {
        this.city = city;
    }
    
    public java.lang.String getState() {
        return state;
    }
    
    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.String getZip() {
        return zip;
    }
    
    public void setZip(java.lang.String zip) {
        this.zip = zip;
    }
    
    public java.lang.String getCountry() {
        return country;
    }
    
    public void setCountry(java.lang.String country) {
        this.country = country;
    }
    
    public java.lang.String getWebPage() {
        return webPage;
    }
    
    public void setWebPage(java.lang.String webPage) {
        this.webPage = webPage;
    }
    
    public java.lang.String getPassword() {
        return password;
    }
    
    public void setPassword(java.lang.String password) {
        this.password = password;
    }
    
    public java.lang.String getHomePhone() {
        return homePhone;
    }
    
    public void setHomePhone(java.lang.String homePhone) {
        this.homePhone = homePhone;
    }
    
    public java.lang.String getDepartment() {
        return department;
    }
    
    public void setDepartment(java.lang.String department) {
        this.department = department;
    }
    
    public java.lang.String getJobTitle() {
        return jobTitle;
    }
    
    public void setJobTitle(java.lang.String jobTitle) {
        this.jobTitle = jobTitle;
    }
    
    public java.lang.String getIMAddress() {
        return IMAddress;
    }
    
    public void setIMAddress(java.lang.String IMAddress) {
        this.IMAddress = IMAddress;
    }
}
